FROM python:3.12.10-bullseye

# Copy code over
COPY . .

# Clean up the default home directory and set up a new one
ENV GITHUB_WORKSPACE=/home
ENV GITHUB_REPOSITORY=hinkleydev/sade-ci
ENV GITHUB_REF=refs/head/main

RUN rm -rf /home && mkdir /home
WORKDIR /home

# Clone the example repository
RUN git clone https://github.com/hinkleydev/sade-ci.git .

# Install dependencies
RUN pip install -r /requirements.txt

# Generate the docs
RUN python3 /app.py > /log.txt
RUN mv /log.txt $GITHUB_WORKSPACE/docs/log.txt

# Serve the docs
EXPOSE 8080
ENTRYPOINT ["python3", "-m", "http.server", "-d", "docs"]