name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install pip packages # Confirm all packages work with the latest python version
        run: pip install -r requirements.txt
