name: Request UAT rebuild

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "uat" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  request:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      actions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send curl request
        run: curl -L -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer {{ GITHUB_TOKEN }}" -H "X-GitHub-Api-Version:2022-11-28"   https://api.github.com/repos/hinkleydev/sade-ci/actions/workflows/build.yml/dispatches -d '{"ref":"main"}'